CREATE TABLE MEDICAMENTOS(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(150)NOT NULL,
	TIPO CHAR(10) NOT NULL,
	
	CONSTRAINT PK_MEDICAMENTOS PRIMARY KEY (ID)
);

insert into MEDICAMENTOS (nome,DESCRICAO,TIPO)values('Acebrofilina ','Acebrofilina 10mg/ml 120ml - adulto ','FR')

select * from MEDICAMENTOS

alter table MEDICAMENTOS
ADD LOCAL_ VARCHAR(100) 

UPDATE MEDICAMENTOS
SET LOCAL_ = 'UBS DR. NÉVIO OZZETTI'
WHERE ID = 1
